#!/bin/sh

# This file is used to configurate the cds command
# Type "cdsconfig -h / --help" further information

# Written by Fenny Zhang
# Last revise: 30th Nov, 2013

# The name of the source file
filename="/home/fenny/.FE_CDS_NewShortCut"

# The following information is used when there is no argument in input
PrintUsage()
{
	echo ""
	echo " CDS lack of certain argument."
	echo " Refer to cds -h / --help for further information."
	echo ""
}

PrintHelp()
{
	echo " Help page "
	echo " CDS can get to a restored directory using FE_CDS_NewShortCuts"
}

PrintErrorMessage()
{
	echo ""
	echo " The FE_CDS_NewShortCut you typed does not exist in current configuration. "
	echo ""
}

ListShortcuts()
{
	# The line number used in count
	FE_CDS_count=1

	echo ""
	echo " Following configurations are available now: "
	echo ""
	while read FE_CDS_line
	do

		# Delete comment lines and empty lines

		if [ "${FE_CDS_line%%\ *}" = "#" ]; then
			continue
		elif [ "$FE_CDS_line" = "" ]; then
			continue
		fi

		# Split the line into three parts: FE_CDS_NewShortCut, directory and document
		
		FE_CDS_FE_CDS_NewShortCut=${FE_CDS_line%%~*}
		FE_CDS_targetDir="${FE_CDS_line#*~}"
		FE_CDS_directory="${FE_CDS_targetDir%~*}"
		FE_CDS_document="${FE_CDS_line##*~}"

		echo "  $FE_CDS_count)\tSHCT = $FE_CDS_FE_CDS_NewShortCut\tDIR = $FE_CDS_directory"
		echo "  \tDescription: $FE_CDS_document"
		echo ""

		FE_CDS_count=$(( $FE_CDS_count + 1 ))

	done < "$filename"
	
	echo " Please type \"cds SHCT\" to change your directory"
	echo ""

}

# Initialize variables
	
	# The flag for not sufficient argument
	NAflag=1

# See the extra options
if [ $# -lt 1 ]; then
	NAflag=1
else
	while [ $# -gt 0 ]
	do
		option="$1"
		shift
		case "$option" in
			"-l"|"--list")
				ListShortcuts $1;
				exit 1;;
			"-h"|"--help")
				PrintHelp;
				exit 1;;
			"-s"|"--FE_CDS_NewShortCut")
				FE_CDS_NewShortCut=$1;
				NAflag=0;
				shift;;
			"-c"|"--comment")
				comment="$1";
				shift;;
			"-r"|"--remove")
				FE_CDS_Remove="$1";
				NAflag=0;
				shift;;
			*);;
		esac
	done
fi

if [ $NAflag -eq 1 ]; then
	PrintUsage
	exit 0
fi

if [ "$FE_CDS_Remove" != "" ]; then

	# Initialize the line counter
	FE_CDS_lineNum=0

	# Initialize the number of lines of comment
	FE_CDS_CommentLine=0

	while read line
	do

		# Get current line number
		FE_CDS_lineNum=$(( $FE_CDS_lineNum+1 ))

		# Delete comment lines and empty lines

		if [ "${line%%\ *}" = "#" ]; then
			continue
		elif [ "$line" = "" ]; then
			continue
		fi

		# Once get out of the comment area, restore the number of comment lines
		if [ $FE_CDS_CommentLine -eq 0 ]; then
			FE_CDS_CommentLine=$(( $FE_CDS_lineNum-1 ))
		fi

		# Split the line into three parts: FE_CDS_NewShortCut, directory and document
		
		FE_CDS_RemoveShortCut=${line%%~*}

		if [ "$FE_CDS_Remove" = "$FE_CDS_RemoveShortCut" -o "$FE_CDS_Remove" = "$(( $FE_CDS_lineNum-$FE_CDS_CommentLine))" ]; then
			sed -i ${FE_CDS_lineNum}d $filename
			exit 1
		fi

	done < "$filename"

fi

if [ "$FE_CDS_NewShortCut" != "" ]; then
	
	if [ "$comment" = "" ]; then
		comment="Added at "$(date)
	fi
	
	echo "$FE_CDS_NewShortCut~$PWD~$comment" >> "$filename"

fi
